Repository NUSGreyhats/NUSGreyhats.github.io, pull requests merged in 2021-10, with the labels that each got.

#14 Update New-site
  content/posts/secweds/ay2122s1/sw0109.md
  content/posts/secweds/ay2122s1/sw1108.md
  content/posts/secweds/ay2122s1/sw1808.md
  content/posts/secweds/ay2122s1/sw2508.md
  data/team.yml
Labels: enhancement, hacktoberfest-accepted

#15 Update team.yml
  data/team.yml
Labels: hacktoberfest-accepted

#17 Update team.yml
  data/team.yml
Labels: hacktoberfest-accepted

#19 Update team.yml
  data/team.yml
Labels: hacktoberfest-accepted

#30 Update sec wed pages
  content/posts/secweds/ay2122s1/sw0311.md
  content/posts/secweds/ay2122s1/sw2010.md
  content/posts/secweds/ay2122s1/sw2710.md
Labels: enhancement
